ARG NODE_VERSION="8.10.0"
FROM node:$NODE_VERSION

WORKDIR /app

ADD ./servicec/package.json /app
RUN set -uex; \
    npm install --production; \
    rm -rf /root/.npm;

ADD ./servicec /app

USER nobody
EXPOSE 6002
CMD ["/usr/local/bin/node", "/app/index.js"]
