version: '3.8'

volumes:
  postgres_data:

networks: 
  ap:
    external: true

services:
  postgres:
    deploy:
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.25"
      #     memory: 128M
      # restart_policy:
      #   condition: any
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    image: postgres
    tty: true
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - ap

  keycloak:
    depends_on:
      - postgres
    deploy:
      replicas: 1
      # resources:
      #   limits:
      #     cpus: '1.50'
      #     memory: 1024M
      #   reservations:
      #     cpus: '0.05'
      #     memory: 128M
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    image: koolwithk/keycloak-arm:16.0.0
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8080:8080
    networks:
      - ap